In [26]:
import geopandas as gpd
import pandas as pd
from pathlib import Path

In [23]:
input_dir = Path.cwd() / "input"
output_dir = Path.cwd() / "output"

In [ ]:
primair = input_dir / "Primaire_keringen" / "geo_infrastructuur_primaire_keringen.shp"
niet_primair = (
    input_dir
    / "Niet_primaire_keringen"
    / "geo_infrastructuur_niet_primaire_keringen.shp"
)
doorbraak_locaties_primair = (
    input_dir
    / "Doorbraaklocaties"
    / "geo_gebiedsindeling_doorbraaklocaties_primair.shp"
)
doorbraak_locaties_regionaal = (
    input_dir
    / "Doorbraaklocaties"
    / "geo_gebiedsindeling_doorbraaklocaties_regionaal.shp"
)

dijkringen = input_dir / "Dijkringen" / "geo_infrastructuur_dijkringen.shp"

In [31]:
scenario_list = pd.read_excel(input_dir / "scenariolist.xlsx")
scenario_manager = pd.read_excel(input_dir / "scenmanager_compare.xlsx")

In [25]:
gdf_primair = gpd.read_file(primair)
gdf_niet_primair = gpd.read_file(niet_primair)
gdf_doorbraak_locaties_primair = gpd.read_file(doorbraak_locaties_primair)
gdf_doorbraak_locaties_regionaal = gpd.read_file(doorbraak_locaties_regionaal)
gdf_dijkringen = gpd.read_file(dijkringen)

In [33]:
scenario_list

,Scenario ID,Scenario Identificatie,Scenarionaam,Scenariodatum,Projectnaam,Eigenaar overstromingsinformatie,Beschrijving scenario,Versie resultaat,Motivatie rekenmethode,Doel,...,Klimaatscenario,Dreigende overstroming,linkurl,gislink,Unnamed: 96,hulp,hulp.1,hulp.2,hulp.3,hulp.4
0,Scenario ID,Scenario Identificatie,Scenarionaam,Scenariodatum,Projectnaam,Eigenaar,Beschrijving scenario,Versie resultaat,Motivatie rekenmethode,Doel scenario,...,Klimaatscenario,Dreigende overstroming,linkurl,gislink,NaN,namespace,minx,miny,maxx,maxy
1,19784,6,+0.0bres10ZP7.5uuri_2,2019-06-06 00:00:00,HHNK ROR2,HHRS Hollands Noorderkwartier,Overstromingsscenario,,Nauwkeurigere resultaten,Ten behoeve van het HWBP zijn in 2015 door Nel...,...,NaN,0,https://basisinformatie-overstromingen.nl/geos...,Overstromingsscenario met id 19784,NaN,LIWO_Regionaal,114010.0,493025.0,116025.0,494305.0
2,19786,0,+ 0.0 bres 11 ZD Hanepadsluis_2,2015-09-11 00:00:00,HHNK ROR2,HHRS Hollands Noorderkwartier,Overstromingsscenario,,Nauwkeurigere resultaten,Ten behoeve van het HWBP zijn in 2015 door Nel...,...,NaN,0,https://basisinformatie-overstromingen.nl/geos...,Overstromingsscenario met id 19786,NaN,LIWO_Regionaal,115725.0,493020.0,119775.0,498400.0
3,19779,1,"+0,0 bres 15 72 uur_2",2019-06-06 00:00:00,HHNK ROR2,HHRS Hollands Noorderkwartier,Overstromingsscenario,,Nauwkeurigere resultaten,Ten behoeve van het HWBP zijn in 2015 door Nel...,...,NaN,0,https://basisinformatie-overstromingen.nl/geos...,Overstromingsscenario met id 19779,NaN,LIWO_Regionaal,123140.0,487865.0,129735.0,492280.0
4,19781,3,+0.0 bres16 TDO 72 uur 2O_2,2019-06-06 00:00:00,HHNK ROR2,HHRS Hollands Noorderkwartier,Overstromingsscenario,,Nauwkeurigere Resultaten,Ten behoeve van het HWBP zijn in 2015 door Nel...,...,NaN,0,https://basisinformatie-overstromingen.nl/geos...,Overstromingsscenario met id 19781,NaN,LIWO_Regionaal,119420.0,491175.0,121585.0,493245.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5142,115791,BRS OV basisscenario Dinkel,BRS OV basisscenario Dinkel,2025-07-29 00:00:00,Bovenregionale Stresstest Overijsselse Vecht,Provincie Overijssel,Bovenregionale stresstest Overijsselse Vecht b...,NaN,Best beschikbare voor complexe integrale water...,Bovenregionale stresstest Overijsselse Vecht b...,...,NaN,0,https://basisinformatie-overstromingen.nl/geos...,Overstromingsscenario met id 115791,NaN,LIWO_BovenRegionaleStresstest,182000.44,490500.44,206000.44,519250.44
5143,115798,BRS_Zeeland,Zeeland_basisscenario,2025-07-01 00:00:00,Bovenregionale stresstest wateroverlast,Provincie Zeeland,Basisgebeurtenis voor landelijk waterbeeld vo...,NaN,Tygron,Bovenregionale stresstest wateroverlast,...,NaN,0,https://basisinformatie-overstromingen.nl/geos...,Overstromingsscenario met id 115798,NaN,LIWO_BovenRegionaleStresstest,182000.45,490500.45,206000.45,519250.45
5144,115815,BRS OV basisscenario Kostverlorenzijl,BRS OV basisscenario Kostverlorenzijl,2025-08-08 00:00:00,Bovenregionale Stresstest Overijsselse Vecht,Provincie Overijssel,Bovenregionale stresstest Overijsselse Vecht b...,NaN,Best beschikbare voor complexe integrale water...,Bovenregionale stresstest Overijsselse Vecht b...,...,NaN,0,https://basisinformatie-overstromingen.nl/geos...,Overstromingsscenario met id 115815,NaN,LIWO_BovenRegionaleStresstest,182000.46,490500.46,206000.46,519250.46
5145,115820,BRS OV basisscenario Radewijkerbeek,BRS OV basisscenario Radewijkerbeek,2025-07-29 00:00:00,Bovenregionale Stresstest Overijsselse Vecht,Provincie Overijssel,Bovenregionale stresstest Overijsselse Vecht b...,NaN,Best beschikbare voor complexe integrale water...,Bovenregionale stresstest Overijsselse Vecht b...,...,NaN,0,https://basisinformatie-overstromingen.nl/geos...,Overstromingsscenario met id 115820,NaN,LIWO_BovenRegionaleStresstest,182000.47,490500.47,206000.47,519250.47
5146,115833,BRS OV basisscenario Kampen Noord,BRS OV basisscenario Kampen Noord,2025-08-08 00:00:00,Bovenregionale Stresstest Overijsselse Vecht,Provincie Overijssel,Bovenregionale stresstest Overijsselse Vecht b...,NaN,Best beschikbare voor complexe integrale water...,Bovenregionale stresstest Overijsselse Vecht b...,...,NaN,0,https://basisinformatie-overstromingen.nl/geos...,Overstromingsscenario met id 115833,NaN,LIWO_BovenRegionaleStresstest,182000.48,490500.48,206000.48,519250.48

In [ ]:
display(gdf_doorbraak_locaties_primair.head())
display(gdf_primair.head())
display(gdf_niet_primair.head())
display(gdf_doorbraak_locaties_primair.head())
display(gdf_doorbraak_locaties_regionaal.head())
display(gdf_dijkringen.head())

,gid,id,dijkringnr,naam,code,x,y,keuze,cascade,LT30,F30T300,F300T3000,F3000T30K,GT30K,notify,geometry
0,1,1,1,Jachthaven,PRIM,206791.0,609827.0,0,None,0,1,1,1,1,NULL,POINT (206791.000 609827.000)
1,2,2,1,Noordzee,PRIM,205564.0,611746.0,0,None,0,0,0,0,2,NULL,POINT (205564.000 611746.000)
2,3,3,1,Maximaal Scenario,PRIM,206960.0,610870.0,0,None,0,0,0,0,1,NULL,POINT (206960.000 610870.000)
3,4,4,2,Nes,PRIM,180600.0,606000.0,0,None,0,1,1,1,1,NULL,POINT (180600.000 606000.000)
4,5,5,2,Hollum,PRIM,172274.0,604623.0,0,None,0,1,1,1,1,NULL,POINT (172274.000 604623.000)

,TRAJECT_ID,TRAJECT_DL,Shape_Leng,DUIDING,klasse,KANS,geometry
0,1-1,001002,9160.156374,Extreem kleine kans: < 1/30.000 per jaar,5.0,7874016.0,"LINESTRING (209653.000 610745.000, 209653.509 ..."
1,1-2,001001,3915.212676,Kleine kans: 1/300 tot 1/3.000 per jaar,3.0,358.0,"LINESTRING (206219.000 609839.000, 206219.236 ..."
2,10-1,010014,5651.075246,Zeer kleine kans: 1/3.000 tot 1/30.000 per jaar,4.0,3115.0,"LINESTRING (202231.127 511585.388, 202211.844 ..."
3,10-1,010013,1724.460675,Kleine kans: 1/300 tot 1/3.000 per jaar,3.0,1042.0,"LINESTRING (200717.949 515831.240, 200702.531 ..."
4,10-1,010016,2426.830269,Zeer kleine kans: 1/3.000 tot 1/30.000 per jaar,4.0,11099.0,"LINESTRING (200190.454 502566.659, 200205.078 ..."

,NAAM,Beheerder,KENMERK_V2,Shape_Leng,kansk,Provincie,Type,Soort,Normfreq,Opmerkinge,sign,geometry
0,Meppelerdiep,Drents Overijsselse Delta,None,1.908598e+08,2,Overijssel,regionaal - ander water kerend,dijk/kade,1:100,None,1.0,"LINESTRING Z (207512.884 522906.352 0.000, 207..."
1,Meppelerdiep,Drents Overijsselse Delta,None,5.046290e+08,2,Overijssel,regionaal - ander water kerend,dijk/kade,1:100,None,1.0,"LINESTRING Z (206710.507 521965.527 0.000, 206..."
2,Meppelerdiep,Drents Overijsselse Delta,None,4.628959e+08,2,Overijssel,regionaal - ander water kerend,dijk/kade,1:100,None,1.0,"LINESTRING Z (211454.623 522058.751 0.000, 211..."
3,Meppelerdiep,Drents Overijsselse Delta,None,8.927394e+08,2,Overijssel,regionaal - ander water kerend,dijk/kade,1:100,None,1.0,"LINESTRING Z (201338.768 517152.194 0.000, 201..."
4,Sallandse weteringen,Drents Overijsselse Delta,None,5.215699e+08,2,Overijssel,regionaal - ander water kerend,dijk/kade,1:100,None,1.0,"LINESTRING Z (202451.098 503283.356 0.000, 202..."

,gid,id,dijkringnr,naam,code,x,y,keuze,cascade,LT30,F30T300,F300T3000,F3000T30K,GT30K,notify,geometry
0,1,1,1,Jachthaven,PRIM,206791.0,609827.0,0,None,0,1,1,1,1,NULL,POINT (206791.000 609827.000)
1,2,2,1,Noordzee,PRIM,205564.0,611746.0,0,None,0,0,0,0,2,NULL,POINT (205564.000 611746.000)
2,3,3,1,Maximaal Scenario,PRIM,206960.0,610870.0,0,None,0,0,0,0,1,NULL,POINT (206960.000 610870.000)
3,4,4,2,Nes,PRIM,180600.0,606000.0,0,None,0,1,1,1,1,NULL,POINT (180600.000 606000.000)
4,5,5,2,Hollum,PRIM,172274.0,604623.0,0,None,0,1,1,1,1,NULL,POINT (172274.000 604623.000)

,gid,id,regio,naam,code,x,y,LT30,F30T300,F300T3000,F3000T30K,GT30K,notify,geometry
0,699,699,Waterlandseboezem,Noordhollandsch Kanaal 3249,REG,125218.0186,499690.6223,1,0,0,0,0,NULL,POINT (125218.019 499690.622)
1,700,700,Waterlandseboezem,Noordhollandsch Kanaal 3736,REG,125142.9871,499215.6273,1,0,0,0,0,NULL,POINT (125142.987 499215.627)
2,701,701,Waterlandseboezem,Noordhollandsch Kanaal 4162,REG,125121.4076,498788.1023,1,0,0,0,0,NULL,POINT (125121.408 498788.102)
3,702,702,Waterlandseboezem,Noordhollandsch Kanaal 4587,REG,125109.9980,498362.8220,1,0,0,0,0,NULL,POINT (125109.998 498362.822)
4,703,703,Waterlandseboezem,Noordhollandsch Kanaal 5018,REG,125118.5537,497934.5432,1,0,0,0,0,NULL,POINT (125118.554 497934.543)

,OBJECTID,DIJKRINGNR,DIJKRING,BEHEERDER,geometry
0,85,77,Roermond 3,Waterschap Roer en Overmaas,"POLYGON ((194334.266 355701.656, 194364.406 35..."
1,82,75,Buggenum,Waterschap Peel en Maasvallei,"POLYGON ((196463.344 360759.781, 196569.516 36..."
2,86,76a,Roermond 2,Waterschap Roer en Overmaas,"POLYGON ((196070.453 355602.000, 196179.547 35..."
3,84,76c,Roermond 4,Waterschap Roer en Overmaas,"POLYGON ((196671.719 356818.406, 196701.594 35..."
4,81,74,Neer,Waterschap Peel en Maasvallei,"POLYGON ((197906.359 363683.406, 198061.922 36..."

In [ ]:
layers = [
    gdf_primair,
    gdf_niet_primair,
    gdf_doorbraak_locaties_primair,
    gdf_doorbraak_locaties_regionaal,
    gdf_dijkringen,
]
for layer in layers:
    if "geom" in layer.columns:
        layer.drop(columns=["geom"], inplace=True)

In [ ]:
driver = "GPKG"
gdf_primair.to_file(
    output_dir / "kansendatabase.gpkg", driver=driver, layer="primaire_keringen"
)
gdf_niet_primair.to_file(
    output_dir / "kansendatabase.gpkg", driver=driver, layer="niet_primaire_keringen"
)
gdf_doorbraak_locaties_primair.to_file(
    output_dir / "kansendatabase.gpkg",
    driver=driver,
    layer="doorbraak_locaties_primair",
)
gdf_doorbraak_locaties_regionaal.to_file(
    output_dir / "kansendatabase.gpkg",
    driver=driver,
    layer="doorbraak_locaties_regionaal",
)
gdf_dijkringen.to_file(
    output_dir / "kansendatabase.gpkg", driver=driver, layer="dijkringen"
)